### ISSUE TITLE
New version of ionic is breaking (at least on large screens).

### ISSUE THREAD

**Issue by uriberto** [Tommertom/svelte-ionic-app#1]
I believe you just need to update your CDN to "@ionic/core@4.6.2" instead of "@ionic/core".

**Comment by Tommertom** [comment]
Hi @uriberto, thx for this. I haven't been active for a while, but your comment is very relevant.

I changed the CDN and actually used 4.11.10 which seems to work too.

Sorry about not responding earlier.
