### ISSUE TITLE
Update the demo app to Svelte 4 (keep in sync with the create option)

### ISSUE THREAD

**Issue by ptmkenny** [Tommertom/svelte-ionic-app#101]
When you run  `npm create ionic-svelte-app@latest`, you get a Svelte 4 app.

However, the `demo-app` in this repo is still on Svelte 3.  It would be great to keep the demo-app `package.json` in sync with the repo's `package.json` to ensure the examples work as expected.

Potentially part of https://github.com/Tommertom/svelte-ionic-app/issues/93

**Comment by Tommertom** [comment]
Done as per your own PR. Thanks
