### ISSUE TITLE
Update demo-app to superforms v2

### ISSUE THREAD

**Issue by ptmkenny** [Tommertom/svelte-ionic-app#103]
The demo-app Input example is based on superforms v1.  It would be great to update it to superforms v2.

I was confused because I cut-and-paste the example code and it didn't work in my app; then I realized it was because I had superforms 2, not 1.

**Comment by Tommertom** [comment]
Ok - I haven't seen that one. It can become quite cumbersome for me to keep up with all the changes in other libraries. So I wouldn't find it a big issue to do a code comment with respect to that so people are warned.

The thing with upgrading the demo app is that it needs to be tested.  For me the priority with ionic-svelte is still rethinking the architecture as some fundamentals are not there - most notably the lacking near-native animations on routing.

**Comment by ptmkenny** [comment]
PR is merged; this can be closed.
