### ISSUE TITLE
The minorest of issues: Wrong cursor

### ISSUE THREAD

**Issue by tomkahn** [Tommertom/svelte-ionic-app#11]
On desktop it doesn't give me the hand-cursor (👆) when hovering over the menu items on the left but the "select text"-one (I) instead. An unforgivable mistake, but other than that great project!

**Comment by Tommertom** [comment]
Thx. Will look into it. Appreciate all feedback.

**Comment by Tommertom** [comment]
Hi @tomkahn 
Can't replicate.. This is what I see on my Win10 Chrome 
https://www.youtube.com/watch?v=PaNjpi5uhR0
What are your specs?
Regards
Tom

**Comment by tomkahn** [comment]
Windows 10, Brave Version 1.12.112 Chromium: 84.0.4147.125 (64-bit)

https://photos.app.goo.gl/rndZF17TkVA5apSu5

**Comment by Tommertom** [comment]
Thx, 

I think your CPU is broken.... You need to put some chewing gum on it, to cool it....

Just kidding, going to check on other devices later on.

To be continued...

Tom

**Comment by Tommertom** [comment]
CAn you try? I forced a pointer

**Comment by tomkahn** [comment]
Works! ✅

**Comment by Tommertom** [comment]
Thx
