### ISSUE TITLE
segmented select

### ISSUE THREAD

**Issue by tconley** [Tommertom/svelte-ionic-app#13]
I'd love to see an example implementation of ion-select with segmented buttons, with ability to select single and multiple.

Here's an example from a paid framework:
https://docs.mobiscroll.com/angular/segmented#using-with-ionic
![image](https://user-images.githubusercontent.com/1893207/90493673-7ef8cd00-e0f7-11ea-9075-1025a5db0b6a.png)

Here's an ionic discussion where they basically said no to making this part of segment, and suggested it be a use case for ion-select. 
https://github.com/ionic-team/ionic-framework/issues/11985#issuecomment-428649602

**Comment by Tommertom** [comment]
Hi @tconley ,

Thank you for raising the issue. Do you know of a non-commercial implementation of this feature? Then I can consider integrating it as option.

**Comment by Tommertom** [comment]
Closing. There is a solution given in the Ionic Forum

https://forum.ionicframework.com/t/ion-select-style-like-segment-buttons/194624/4

**Comment by tconley** [comment]
Yes, that's me posting over there :) Once I polish off this component I'll submit a pull request. Great project!
