### ISSUE TITLE
NPM failure

### ISSUE THREAD

**Issue by ComedyTomedy** [Tommertom/svelte-ionic-app#24]
NPM 8.1.4

Installation died with an error, unless I did this first:

```
npm install -g agentkeepalive --save
```

The error message:

```
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2022-02-08T15_06_10_986Z-debug.log
```

**Comment by ComedyTomedy** [comment]
I'm not really an npm, expert, but maybe installing this locally in the project, as a dev dependency is the right thing to do?

    npm install agentkeepalive --save-dev

**Comment by Tommertom** [comment]
Hey @ComedyTomedy  - sorry for leaving you without comments. Not sure why agentkeepalive is needed. Never encountered this issue. As you do a global install, it seems to be related to network stuff - also looking at your error message.

Hope it still worked. Right now I am focussing on getting Ionic 6 with Svelte and Vite going. (using npm create vite@latest). I think then we are in a totally new situation with respect to packages.

**Comment by ComedyTomedy** [comment]
Yeah don't worry. I think I was just suggesting adding a dependency in case it helped someone else. Good luck with everything!
