### ISSUE TITLE
svelte-custom-elements

### ISSUE THREAD

**Issue by joshua1** [Tommertom/svelte-ionic-app#3]
@Tommertom  with this module deprecated, what is the alternative implementation that doesn't use svelte-custom-elements in the services/IonicController.js file. Also will this be updated for Ionic 5. I am interested in using this for mobile app

**Comment by Tommertom** [comment]
Hi, in Ionic 5, the API changes a bit indeed, e.g.  `    import { menuController } from '@ionic/core';`

I haven't upgraded it yet and it will indeed be a breaking change. Let me see if I find the time the coming weeks to work on it. Would be a nice one to do, to keep the project relevant.

Will open issue "ionic 5 upgrade"

Custom elements will continue to work in svelte, so you can go ahead with ionic 4 in the meantime?

**Comment by joshua1** [comment]
@Tommertom  Thanks a lot for the quick reply. I think i will wait for the Ionic % changes, while looking at other things, i am also going to try getting a better understanding of the work you did here with Ionic 4. Well done and Thanks for this. The Ionic team must be made aware of this work here, makes it easier for them to start supporting svelte as a first class framework for Ionic
