### ISSUE TITLE
A nicer logo for this app (touch- & fav-icon) - anyone can help?

### ISSUE THREAD

**Issue by b-d-m-p** [Tommertom/svelte-ionic-app#31]
I can help with that. What are you thinking?

**Comment by b-d-m-p** [comment]
So some combination of the Svelte and Ionic logos, right? I know this uses Vite but things like that change so maybe it's better to leave that out.

**Comment by Tommertom** [comment]
Hi there - thx for reaching out @b-d-m-p 

Will nice to get a better logo.  So if you are able to put something together, that will be great!

Re Vite - I get your point. And less is more indeed.  I surely hope Vite is here to stay, but can be replaced indeed.

Combining the two communities - Svelte and Ionic- is basically also the objective of the project.  Up to the point it becomes so popular that Ionic team embraces it officially. :) 

I thought of mentioning Vite because the project is not supporting SvelteKit. But that does not need to be covered in the logo perse.

**Comment by b-d-m-p** [comment]
Ok! Sounds good! I will get it done this weekend.

**Comment by b-d-m-p** [comment]
Playing around

![image](https://user-images.githubusercontent.com/1300390/177527286-f93691c5-e13d-49ef-9a20-8bb3ffd88db9.png)

**Comment by b-d-m-p** [comment]
![image](https://user-images.githubusercontent.com/1300390/177528311-a4a0f85d-bec8-4cb4-a373-090882097dcf.png)

**Comment by b-d-m-p** [comment]
C

![image](https://user-images.githubusercontent.com/1300390/177529078-4b50b8da-b7d1-419a-b230-352295ef281e.png)

**Comment by b-d-m-p** [comment]
D

![image](https://user-images.githubusercontent.com/1300390/177530891-670011db-6804-4f4f-b4a9-41f8908032c7.png)

**Comment by b-d-m-p** [comment]
E

![image](https://user-images.githubusercontent.com/1300390/177532181-49175819-e4dc-4e3c-b342-cf5787842df8.png)

**Comment by b-d-m-p** [comment]
D is the best but it's going to be unreadable as a favicon. Let me know if you have any other ideas.

**Comment by Tommertom** [comment]
Nice! I would go for C

No dominance from either two - so to say.


What about you?


We can pick two or more and do a vote - on Twitter I reckon?

**Comment by b-d-m-p** [comment]
The only thing with C is that the circle in the middle is missing so it doesn't register as Ionic for me. Also, I think Ionic should be dominant because if you look at Ionic React, Ionic Vue, etc., the library it is written with is like the flavor of Ionic. And ultimately it would be adopted by Ionic so they have a bit more importance. 

Yeah, let's do a poll on Twitter 😃

F

![image](https://user-images.githubusercontent.com/1300390/177536071-f008fa4c-a145-4238-8a09-3ea368634e02.png)

**Comment by Tommertom** [comment]
That makes a nice favicon. 
Let me work on my twitter skills :)

**Comment by Tommertom** [comment]
Quick Q - can you do a PR for a high res version of the logo? Or otherway relay it to me?

**Comment by b-d-m-p** [comment]
![Ionic Svelte logo](https://user-images.githubusercontent.com/1300390/177896067-bc4e9673-fd94-4f77-bb9d-ea941d010b0e.svg)
![Ionic Svelte logo@4x](https://user-images.githubusercontent.com/1300390/177896074-aec71daa-7b3c-4773-9476-91caafb707cb.png)

@Tommertom here you go! Give me your email address and I can add you to the Figma file. 

https://www.figma.com/file/PFtYtKjlSBOPKtKwV82uU7/Ionic-Svelte?node-id=0%3A1

**Comment by b-d-m-p** [comment]
I can make all those favicons, icons and splashscreens if you want. Just let me know. I can do a PR and add them all.

**Comment by Tommertom** [comment]
> I can make all those favicons, icons and splashscreens if you want. Just let me know. I can do a PR and add them all. 

Yes please - go ahead. If you need anything from me, let me know

**Comment by Tommertom** [comment]
> Here's all the other weird things I tried by the way 😆
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/1300390/177896983-d1b4d552-ab37-4d60-b4b3-8a657d9999ae.png">

This is the thought proces?

**Comment by b-d-m-p** [comment]
Kinda, not so much a thought process as just trying many different approaches and see which one works best

**Comment by Tommertom** [comment]
Implemented
