### ISSUE TITLE
Ionic Page transition - how to implement in router?

### ISSUE THREAD

**Issue by Tommertom** [Tommertom/svelte-ionic-app#32]
For page transitions Ionic has this really cool transition which is more than just a single page fly-in - what is happening now.

It looks into the various elements of the incoming component and gives them specific transitions. Like the header-title, the default back-button and the page itself. Also the outoging component gets this special treatment as a whole and for its elements.

For now I have been able to pin down this transition in their code. And here an example link to the transition in ios: https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/transition/ios.transition.ts

The function responsible for adding the transitions to the dom elements seems to be :
```

   const transition = (
      enteringEl: HTMLElement,
      leavingEl: HTMLElement,
      direction: any, // TODO types
      showGoBack: boolean,
      progressAnimation: boolean,
      animationBuilder?: AnimationBuilder
    ) => {
```
(taken from the vue implementation -and I need to check how it relates to the ios.transitions.ts)

The API requires the enteringElement and the leaving element, besides a directions. The showGoBack is related to the BackButton mostly shown top left or top right corner. animationBuilder is I believe a customer animation and the boolean I don't know, but probably not of big interest for now?

So, the question is how to hook this up in Routify. Maybe through the helpers you have? But I also think/fear/believe a more deeper connection might be needed.

Looking for help on how to achieve this.

**Comment by kristianmandrup** [comment]
`routing-store.js`

```svelte
<script>
import { writable } from "svelte/store";
export const routing = writable({});
```

`routing-config.js`

```svelte
<script>
import { routing } from "./stores.js";
import { beforeUrlChange, afterUrlChange } from "@roxi/routify"
$beforeUrlChange((event, route) => {
  routing.update({before: true, event, route})
})

$afterUrlChange((event, route) => {
  routing.update({after: true, event, route})
})
</script>
```

Then create some components that subscribe to the store and activate the transitions?

**Comment by kristianmandrup** [comment]
Interesting article with some patterns here: https://imfeld.dev/writing/svelte_overlapping_transitions and https://blog.logrocket.com/essential-transitions-and-animations-in-svelte/

Looks like the key is to use https://svelte.dev/tutorial/key-blocks like in https://stackoverflow.com/questions/69186922/transition-when-cycling-through-store-in-svelte

**Comment by kristianmandrup** [comment]
Note that in routify 3, they are called hooks, not helpers https://v3.ci.routify.dev/docs#guide/concepts/hooks

Elements on individual pages can be accessed via context and nodes https://v3.ci.routify.dev/docs#guide/concepts/nodes
Perhaps meta and preloading could be useful to tap into? https://v3.ci.routify.dev/docs#guide/concepts/meta https://v3.ci.routify.dev/docs#guide/concepts/preloading

**Comment by Tommertom** [comment]
Hi @kristianmandrup  - thank you so much for this! I will study more carefully in the coming days/week - busy on something else (=J O B). But really appreciate the effort!

**Comment by Tommertom** [comment]
https://youtu.be/ua6gE2zPulw

Placeholder - Geoff Rich on element transitions

**Comment by kristianmandrup** [comment]
By chance, I just discovered the new PageTransition API available in Chrome beta (ie native support).

https://www.youtube.com/watch?v=JCJUPJ_zDQ4 - Bringing page transitions to the web
https://hyva.io/blog/news/page-transition-api-at-the-hyvacamp-2022-hackathon.html

**Comment by kristianmandrup** [comment]
Oh, we discovered the same PageTransition API independently :)

**Comment by kristianmandrup** [comment]
Aha, here is a Svelte demo not using the Page Transition API - https://github.com/pngwn/svelte-travel-transitions

**Comment by kristianmandrup** [comment]
All the info for his presentation: https://geoffrich.net/posts/svelte-london-2022/
And here the repo for his demo: https://github.com/geoffrich/sveltekit-shared-element-transitions

I would think that his code would just need to hooked up to a wrapper around roxify router which provides slightly more information and flexibility.

**Comment by kristianmandrup** [comment]
For Routify v3

```js
 * @typedef { function({route: Route}): any } BeforeUrlChangeCallback
 * @typedef { function({
 *   route: Route,
 *   history: Route[]
 * }): any } AfterUrlChangeCallback
```

**Comment by kristianmandrup** [comment]
According to Geoff's code we need the `from` and `to` routes. In the `beforeUrlChange` hook we get the `route` which contains the `router` with the history (where we can get `from`) and the url of the route being navigated `to`

**Comment by kristianmandrup** [comment]
@Tommertom Routify author has just provided [this store](https://github.com/roxiness/routify/issues/477#issuecomment-1232669203) for integration with Page Transition wrapper by @geoffrich .

```js
$: store = {
  from: $activeRoute
  to: $pendingRoute 
  state: $pendingRoute ? 'started'  :  'complete' 
}
```

**Comment by kristianmandrup** [comment]
I've just created this sample repo using the Page Transition wrapper by @geoffrich and routify 3
https://github.com/kristianmandrup/page-transition-app

Could serve as a starting point to build on.

**Comment by Tommertom** [comment]
Hey there

So from the rapid reading I have done I see a few things 
- I will be moving to SvelteKit router, so removing Routify from the main repo.  So that limits my personal appetite to invest in Routify. 
- the key challenge I see, and I am not sure if your solution repos solves it - is that the incoming page transition as well outgoing page transition needs all sorts of animating stuff going on INSIDE the pages. So not just the full page transitioning, but some default components (if present) to animate as well. 

Example - if the outgoing page has a back button, that specific button itself, on top of the page animation, should animate in a bit different way - like defined in https://github.com/ionic-team/ionic-framework/blob/main/core/src/utils/transition/ios.transition.ts

So, I am just curious if that part is included in your setup - and if so, does the node in Routify (let's stick to Routify for this) really refer to the mounted components?

**Comment by kristianmandrup** [comment]
Hi @Tommertom, from my understanding and investigation, SvelteKit does not currently support Ionic apps. Hence I'm not sure if you can use the SvelteKit Router instead of Routify. 

- https://github.com/sveltejs/kit/issues/5143#issuecomment-1190843804

The example app by @geoffrich as demonstrated in his video showcases the back button and an image on a page being animated independently of the page itself during the page transition. 

This fine-grained animation is supported in https://github.com/kristianmandrup/page-transition-app/blob/main/src/lib/page-transition.ts and https://github.com/kristianmandrup/page-transition-app/blob/main/src/lib/reduced-motion.ts in particular using
- [beforeCallbacks](https://github.com/kristianmandrup/page-transition-app/blob/main/src/lib/page-transition.ts#L107)
- [incomingCallbacks](https://github.com/kristianmandrup/page-transition-app/blob/main/src/lib/page-transition.ts#L113)
- [afterCallbacks](https://github.com/kristianmandrup/page-transition-app/blob/main/src/lib/page-transition.ts#L116)

(If I recall correctly)

**Comment by Tommertom** [comment]
Sveltekit and Ionic (my lib that is) go well together as long as sveltekit runs SPA mode

I have it running - I just need to go to their latest breaking release and then implement it

**Comment by kristianmandrup** [comment]
Very cool :) SvelteKit sure moves fast... 
Very exciting!

**Comment by Tommertom** [comment]
Closing this issue as I am moving the ionic package related stuff to the ionic-svelte npm package repo

If you haven't seen this - please check out `ionic-svelte` on npm. Or create your SvelteKit Ionic app via the CLI: `npm create ionic-svelte-app@latest`.
