### ISSUE TITLE
What are the advantages of routify vs. window.location.href?

### ISSUE THREAD

**Issue by burggraf** [Tommertom/svelte-ionic-app#34]
I'm very new to Svelte (but loving the simplicity and speed of it so far).  Can you tell me, though, what the advantages are of using `routify` vs. standard html routing for something like `[..fallback].svelte`?

```js
<script lang="ts">
  import { goto } from "@roxi/routify";
  $goto("/");
</script>
```
vs.

```js
<script lang="ts">
window.location.href="/";
</script>
```

**Comment by Tommertom** [comment]
Hi there

Thx for trying this out 

a window.location.href will trigger a full page reload where as a router command won't

In this case (fallback) it might be a big issue, because someone entered a wrong URL.

Or you programmatically triggered a wrong route - in that case, it also does not matter - we need to debug then :)

**Comment by burggraf** [comment]
Gotcha.  This repo rocks.  I'm creating some `Supabase`-specific stuff that I hope to break into a separate `npm` lib that can be easily added in:  https://github.com/burggraf/svelte-ionic-supabase-sidemenu.  Once I get further along I'll host a demo app with the extensions.

**Comment by Tommertom** [comment]
Thx - I will be glad to hear how things have worked out for you.

**Comment by Tommertom** [comment]
I think this can be closed now - although having open issues is mostly a healthy sign ;)

**Comment by burggraf** [comment]
I'm using this repo as a base for a fairly large project now, and it's going very well.  Are you upgrading to the latest SvelteKit release, and if so, when?  And will there a big upgrade curve?

**Comment by burggraf** [comment]
Thanks for this -- I appreciate this POV, basically "if it's working no need to upgrade now."  And it's working extremely well, as I said.  Just let me know where you'd like me to supply feedback and I'll be happy to post my findings as I go.  Thanks for this product!!!

**Comment by Tommertom** [comment]
Hi @burggraf  - bit off topic from this issue, but have you implemented form handling and if so, which libraries did you use to do the validation and error reporting to user? 

I am trying yup for schema and validation. But not yet found a suitable form lib that uses yup to validate ionic forms

**Comment by burggraf** [comment]
I haven't implemented any form handling -- I usually do most of that by hand anyway, sorry.
