### ISSUE TITLE
PWA config

### ISSUE THREAD

**Issue by pedelriomarron** [Tommertom/svelte-ionic-app#35]
Good I've been trying to understand for a couple of hours, what configuration should I do with vite to have PWA.

For example to your demo example, if I wanted to have it in PWA, would I have to add code or just some configuration?
Thank you very much and great job.

edit: I think what I don't understand is how to use the service worker, because I don't see it in your code and I don't know where you are calling it.

**Comment by Tommertom** [comment]
Hi there

there subscribe method in App.svelte invokes the service worker registration. 

https://github.com/Tommertom/svelte-ionic-app/blob/main/src/App.svelte

And pwa.ts does the registration - https://github.com/Tommertom/svelte-ionic-app/blob/main/src/lib/pwa.ts

A bit hidden indeed. And the vite PWA out-of-the-box configurations let's you put in in main.ts. 

But I wanted everything around the PWA happening in a readable so I can use the various things in other places.

The alternative way would be to put the `import { registerSW } from 'virtual:pwa-register'` back in main.ts or App.svelte and then have it call a writable store. But then every component can do a set on it, which I don't want.

**Comment by Tommertom** [comment]
Alternatively I could add a `registerServiceWorker` function to pwa.ts that does nothing more than subscribe to the readable. 

Then there is an explicit calll to a registration which might speak more to the developer's expectation then this. 

What is your recommendation?

**Comment by burggraf** [comment]
My app is working great offline, so the service worker is doing its job.  But what steps do I need to take to force an app refresh when I release a new version?  Will just upping the app version number in package.json force a refresh if the app is cached?

**Comment by burggraf** [comment]
I just tested it and it seems to update automatically.  Sweet.

**Comment by Tommertom** [comment]
Yup

There is an update event you can monitor so you can waen your users as the refresh is pretty aggressive


And indeed the refresh trigger comes from a new build which generates all sorts of new hashes the existing sw will pickup

Not having a proper update routine in your app before deploying as pwa will leave you with a manual intervention needed by your users to update

Or lots of time until stuff gets stale in the cache

**Comment by pedelriomarron** [comment]
thank you

**Comment by burggraf** [comment]
Creating an app with:  `npm create ionic-svelte-app@latest` no longer includes any pwa code?  The `src/lib` folder is now empty when creating a new project.

**Comment by burggraf** [comment]
The `lib` folders were removed by this commit on Feb 15:
https://github.com/Tommertom/svelte-ionic-app/commit/4e6e7fe24edaba793a3a493de94cf5896b93ff82
