### ISSUE TITLE
Errors running menu demo

### ISSUE THREAD

**Issue by shaunmulligan** [Tommertom/svelte-ionic-app#36]
When running the menu demo I get the following error:
```
The requested module '/src/lib/ionic/svelte/index.ts' does not provide an export named 'getIonicMenu'
```
Other demos work as expected :D

**Comment by Tommertom** [comment]
Hey there
Thanks for reporting. That import can be removed as it is not used.
Is it working then?
Thx for the feedback

**Comment by shaunmulligan** [comment]
Alright, cool it seems to work after removing that
