### ISSUE TITLE
Nagivation forwards animation

### ISSUE THREAD

**Issue by ollydixon** [Tommertom/svelte-ionic-app#37]
Awesome job; love it!

Any idea how we can get forwards navigation animations working?

Also; how do we deploy to web?

**Comment by Tommertom** [comment]
Hi thx for the compliments. We live to serve :)

Not sure what you mean with forward navigation animations - there is a non-Ionic rudimentary animation for pages implemented in IonPage.svelte. If that is what you are looking for?

As to "deploy to web". This depends on where you want to deploy to. I am using Firebase, but you easily go to Netlify, Vercel etc. That is not an Ionic thingy. Once you build the assets for production (npm run prod), the goodies to put on the webserver are in /dist/client  folder

**Comment by ollydixon** [comment]
I deploy via standard container, gcloud :-)

But what I mean is, what are the steps to deploy web, it's just the same static code?

**Comment by Tommertom** [comment]
Hi - yes. I myself build the assets using the npm run prod command and then use firebase cli to upload the dist/client files to firebase hosting. So fully static hosting of html, css, js and other files

Maybe even easier then setting up gcloud container?

And the SPA rewrite rules are immediately set properly

**Comment by Tommertom** [comment]
I think this can be closed now - although having open issues is mostly a healthy sign ;)
