### ISSUE TITLE
`vite build` fails with error

### ISSUE THREAD

**Issue by burggraf** [Tommertom/svelte-ionic-app#43]
When I run `vite build` the build fails with the following error:

```
[vite-plugin-pwa:build] Missing "./preload-helper" export in "vite" package
error during build:
Error: Missing "./preload-helper" export in "vite" package
```

**Comment by burggraf** [comment]
I just realized `npm run build` does not fail, but since this just calls `vite build` why would `npm run` work?

**Comment by Tommertom** [comment]
No clue - but not specific to this project I would say

**Comment by burggraf** [comment]
You can close this.  Thanks.
