### ISSUE TITLE
Problem with Tabs component

### ISSUE THREAD

**Issue by Forsakenrox** [Tommertom/svelte-ionic-app#48]
Im not sure why, but tabs component not work.
I copy file structure from example https://github.com/Tommertom/svelte-ionic-app/blob/main/src/routes/components/tabs/ but im still getting error `tab with id: "undefined" does not exist` when i try to make any actions.

![image](https://user-images.githubusercontent.com/11795286/208427059-f5c6e973-167a-4d10-952d-d69383d2eaca.png)

**Comment by Tommertom** [comment]
Hi there,

Can you share a minimal repo? Please note that the ion-tabs interface has changed, and the ionic-svelte demo app does not have the latest version 

Please check -
https://github.com/Tommertom/ionic-svelte-tabs-howto

for the latest API

**Comment by Forsakenrox** [comment]
Thank for example repo, now i see what i need to do
