### ISSUE TITLE
"ion-item-sliding" not working

### ISSUE THREAD

**Issue by grabbels** [Tommertom/svelte-ionic-app#51]
The `<ion-item-sliding>` Ionic element does not work. Items are displayed statically, but do not react to sliding gestures, making them effectively static list items. No errors are thrown and it does not prevent the app from compiling.

**Comment by grabbels** [comment]
Closed this because I realized the elements come from the Ionic 4 framework, however, the ion-item-sliding was already part of v4, so I'm still curious to know what's going on here.

**Comment by Tommertom** [comment]
That's correct -  awaiting resolution in Ionic/core

https://github.com/Tommertom/svelte-ionic-npm/issues/10

**Comment by burggraf** [comment]
I've got this issue too, but it doesn't seem to work in production either, so I'll wait for the fix.

**Comment by Tommertom** [comment]
ok thx - the app will follow system preferences, so if you switch to dark mode overall, it will show in dark mode. So basically overriding system systems is not working as per Ionic API.

**Comment by Tommertom** [comment]
Item Sliding appears to work again in the rebuild demo app?  https://github.com/Tommertom/svelte-ionic-app/issues/93
