### ISSUE TITLE
Errors while trying to run npm run dev

### ISSUE THREAD

**Issue by the-rasmussen** [Tommertom/svelte-ionic-app#7]
I'm trying to run `npm run dev` but I'm getting errors unfortunately.

First I get a runtime error in the browser console saying: `localhost/:1 Uncaught TypeError: Failed to resolve module specifier "@sveltech/routify/tmp/routes"`

In package.json I can see that @sveltech/routify is set to version "next", which npmjs.com says is version 1.1.1-1. That is a rather old version, so I tried updating it and that fixed it. Both 1.8.0 and .1.9.1 worked.

But the I get a new error (hooray?): `localhost/:1 Uncaught (in promise) TypeError: Failed to resolve module specifier "@ionic/core".`

I've tried fixing this by installing @ionic/core via npm. `npm install --save --save-exact @ionic/core@5.2.3`

Doing so gets me this error, which has me stumped:
```
index.mjs:41 Uncaught (in promise) TypeError: Cannot read property 'subscribe' of undefined
    at subscribe (index.mjs:41)
    at get_store_value (index.mjs:46)
    at onComponentLoaded (Route.svelte:72)
```

**Comment by Tommertom** [comment]
Hi @the-rasmussen , thx for reporting the issue. Will try to reproduce from the repo. Sorry about the bad experience.

**Comment by the-rasmussen** [comment]
I updated all the packages to latest and now it works :)

But I kinda think ionic is being included twice now, right? Once via the script tags and once via the esm module imports.

**Comment by Tommertom** [comment]
There is something wrong with the @ionic/core import and the definition in rollup.js.. Still need to experiment to figure.
Have updated the dependencies and now everything is broken :)
So, looking forward to a few evenings having fun. To be continued.

**Comment by Tommertom** [comment]
PR implemented. Thx @the-rasmussen for your support.
