### ISSUE TITLE
Usage without SvelteKit is currently broken (feature request)

### ISSUE THREAD

**Issue by notpushkin** [Tommertom/svelte-ionic-app#72]
Hey, first of all thanks for your wonderful project!

I've tried setting it up with Routify instead of SvelteKit and found out that `ionic-svelte/components/IonTabs.svelte` depends on SvelteKit's `$app/stores` and `$app/navigation` implementation. This wouldn't be a problem but the main `ionic-svelte/index.ts` module imports it, which causes Vite to fail bundling it:

> **[plugin:vite:import-analysis]** Failed to resolve import "$app/stores" from "node_modules/.pnpm/ionic-svelte@0.5.72/node_modules/ionic-svelte/components/IonTabs.svelte?v=331c4727". Does the file exist?

The workaround I've arrived at is to add a shim:

1. In `vite.config.js`, set `resolve.alias.$app` to `path.resolve(__dirname, "src", "lib", "sveltekit-shim")`
2. In `src/lib/sveltekit-shim`, add following files:

    ```ts
    // navigation.ts
    export function goto(): never {
      throw new Error("Not implemented");
    }
    ```

    ```ts
    // stores.ts
    export const page = {
      subscribe: () => {
        throw new Error("not implemented");
      },
    };
    ```

(I've [tried reimplemening a subset](https://gist.github.com/notpushkin/902acfa948bf0db41fd540740ed57051) of SvelteKit's API, but seeing that legacy tabs implementation is available that's not really necessary)

Perhaps a better solution would be to just remove the `IonTabs` import from index.ts altogether, and update docs to guide to import it like:

```js
import { IonTabs } from "ionic-svelte/components/IonTabs.svelte";
```

**Comment by Tommertom** [comment]
Hi - thanks for the issue. yes indeed I assume the user wants to use SvelteKit, not Svelte with Vite.

I personally don't know why you would want to use an external additional library as a router? Routify v3 is in beta for quite a while now, so imho showing the tech debt if you create too many dependencies. Anyone moving from an existing project to Ionic-svelte will need to do a migration anyway, so why not SvelteKit in SPA mode?

I like your proposal, but introducing it will create a breaking change. I could consider this as part of Ionic 7 migation, if that also creates breaking changes. Then likely devs will be reading docs to understand how to fix it.

**Comment by Tommertom** [comment]
Hey - I get your point. Let me think. If we can do it in a way it does not break things, why not.... I guess it is just a matter of sufficient time to do all the work.

**Comment by Tommertom** [comment]
Hi there - so I followed your advise and removed the imports that require kit.

IonTabs is exported by index.ts, but that will give you a warning. 

Kit users now need to point towards `ionic-svelte/components/IonTabs.svelte` explicitly to get the Kit version.

As the the three "contentious" components require integration with the router - they require a separate implementation for all other routers out there. This is beyond my appetite to develop. But it should be doable for anyone being a big fan of a non-kit router.

Will this work for you @notpushkin  ?

(version 0.5.78 has this)

**Comment by Tommertom** [comment]
And btw, if you dont want file based routing with kit, you can by having a slug at the main route to capture every route requested and then map into the component you want to render...

Hint from Rich Harris

/[...everything]

**Comment by notpushkin** [comment]
@Tommertom hey! Looks fine to me, yeah. Thank you so much!

**Comment by gsxdsm** [comment]
As someone that uses this with Inertiajs, thanks!
