### ISSUE TITLE
Ionic 7

### ISSUE THREAD

**Issue by burggraf** [Tommertom/svelte-ionic-app#73]
What's the status of migrating to Ionic 7?  Is there any valid reason to do this now?

**Comment by burggraf** [comment]
I don't think it's a priority yet, either, as long as new projects created with `svelte-ionic-app` work as is.  If we need to specify a specific version of the ionic framework in the `package.json`, then let us know.

**Comment by Tommertom** [comment]
Released the package with ionic 7.0.2

No big issues

Demo app rewrite is a todo item

**Comment by burggraf** [comment]
Trying to update an existing project gives the following errors:

```
[vite] error while updating dependencies:
Error: Build failed with 3 errors:
src/lib/ionic/svelte/components/defineComponents.ts:83:25: ERROR: Could not resolve "@ionic/core/components/ion-slide"
src/lib/ionic/svelte/components/defineComponents.ts:84:26: ERROR: Could not resolve "@ionic/core/components/ion-slides"
src/lib/ionic/svelte/components/defineComponents.ts:97:33: ERROR: Could not resolve "@ionic/core/components/ion-virtual-scroll"
```

**Comment by Tommertom** [comment]
Which ionic-svelte are you using? 0.5.76 is the latest and fixed defineComponents.ts 

If you want to clear this bug, then you can either remove the entries to the components no longer existing in Ionic/core, or just remove defineComponents.ts as it is legacy code.

**Comment by burggraf** [comment]
I tried to update just by removing `ionic-svelte` and `@ionic/core` from my project and re-adding it, but the `defineComponents` doesn't automatically get updated that way, so I manually commented out the offending lines.  After doing that I still got errors so I just reverted my changes and went back to the older version.  I can try again if you want?  Is there an upgrade guide you want me to follow?

**Comment by burggraf** [comment]
There's no pressing need for me to do this, so if it's not ready/easy to upgrade yet I'm fine with 6.x for now.

**Comment by Tommertom** [comment]
Thx for trying- no upgade guide yet - I will do so as part of upgrading the demo. I think what is there now is just for new projects only.  Will keep you posted.

**Comment by Tommertom** [comment]
For now the migration of the demo is stranded on proper swiper configuration for slides.. 

But the rest was easy:
* npm i ionic-svelte@0.5.77
* npm i @ionic/core@7.0.2 

The changed API for input/text-area is easier but a bit of work refactoring in due course

So work in progress - not released yet

**Comment by burggraf** [comment]
Ironically I just converted an older project to swiper (just in case Ionic 7 support gets finished soon) :)

**Comment by Tommertom** [comment]
![image](https://user-images.githubusercontent.com/16119174/234081823-baf7c782-a5c3-428a-9c27-65b491ef2ce6.png)


I am getting this layout using the styling proposed in the ionic migration guide (angular)

You have the same issue? Would like to see the css for swiper

**Comment by burggraf** [comment]
I'm not having any problems with swiper in my application so far.

**Comment by Tommertom** [comment]
Can you share the CSS you use for `swiper-container` and `swiper-slide`?

**Comment by burggraf** [comment]
I checked and I have no special css on either of those objects.  It's working fine for me.  It's a private project but I'd be happy to let you take a look at it if you DM me.

**Comment by burggraf** [comment]
Here are the slide options I'm using:
```
    const slideOpts = {
        initialSlide: 0,
        speed: 400,
        centeredSlides: true,
        centeredSlidesBounds: true,
    };

```
