### ISSUE TITLE
ion-icon url 

### ISSUE THREAD

**Issue by sbscan** [Tommertom/svelte-ionic-app#80]
I create app with **npm create svelte@latest my-app** and installed via npm.
All other components working but icons not working. Getting the fallowing error in console:
Uncaught TypeError: Failed to construct 'URL': Invalid base URL

**Comment by Tommertom** [comment]
> I create app with **npm create svelte@latest my-app** and installed via npm.
> 
> All other components working but icons not working. Getting the fallowing error in console:
> 
> Uncaught TypeError: Failed to construct 'URL': Invalid base URL

Can you share the code you used and the import statement?

It should be like this:

  import {addCircle} from "ionicons/icons"; 

 <ion-icon icon={addCircle}></ion-icon>
