### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by slynchDev** [Tommertom/svelte-ionic-app#87]
Hello, your widget library looks fantastic. I hope this isn't a dumb question, I'm getting started with capacitor and was wondering how to best use your framework with capacitor? Should I create the project as per your instructions or per the capacitor instructions? Thanks so much

**Comment by Tommertom** [comment]
Thx @slynchDev - does not matter which `npm create`  command you use (such as `npm create ionic-svelte-app@latest`. They can deliver the same, as long as you select the same options.

**Comment by slynchDev** [comment]
Thank you!
