### ISSUE TITLE
ion-select issues when ion-select-options are populated inside an #each loop

### ISSUE THREAD

**Issue by NeilCresswell** [Tommertom/svelte-ionic-app#96]
Have to say I really appreciate svelte-ionic and am heavily into a project that uses it, so thanks for the work on this repo.

The only issue I've encountered that I've not been able to get around is when I want to populate a list of `ion-select-option` elements programmatically in the HTML, iterating through an array using `#each`. The array is loaded at the very start of the `<script>` section, and is immediately available since it's an imported constants file that can be reused elsewhere in the project. In this example, I'm also using `ion-select value={something}` to have a default option selected. Again the value is set at the start of the `<script>` section, and is currently hard-coded for testing purposes.

If I hard-code all of my `ion-select-option` list entries instead of using an `#each` loop, all works as expected, and I can hook changes with `on:ionChange`.

If I use `#each` instead then the `ion-select` input box doesn't display the pre-selected option, which just appears blank, and it remains blank if I programmatically change the selected value after the page has rendered. Hitting the select's drop down does expose all of the programmatically provided options and I can select one, at which point `ion-select` displays the selection, and I can pick a different selection and get the input populated with that. However, as soon as I programmatically change the value, the input goes blank again.

With the hard-coded options list, my default selection displays, and I can programmatically change the value and get a different selection to display too.

This may well be me not understanding something. I usually have to hook `on:ionWillOpen` or `on:ionModalWillPresent` to do a few things for Ionic on most pages, and I experimented with setting the default selection value there too, but that had no effect.

**Comment by Tommertom** [comment]
Thx - do you have a sample repo I can clone to see it happening?

**Comment by NeilCresswell** [comment]
Thanks for the quick reply. I knocked up a quick demo for you and found... that the demo worked.
Mea culpa. I had a coercion bug. Sorry for having taken any of your time. :(

**Comment by Tommertom** [comment]
No worries @NeilCresswell  - I know the feeling and sharing always helps.
